/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
    alias(libs.plugins.springdependencymanagement)
}

dependencies {
    implementation(project(":domain"))
    implementation(libs.bundles.spring.data)
    testImplementation(libs.bundles.testgoodies)
}
