/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
    alias(libs.plugins.springboot)
    alias(libs.plugins.springdependencymanagement)
}

dependencies {
    implementation(project(":controller"))
    implementation(project(":domain"))
    implementation(project(":dynamodb-repository"))
    implementation(project(":gcp-job-data-extractor"))
    implementation(project(":util"))
    implementation(project(":usecases"))
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation(libs.bundles.awssdk)
    implementation(libs.bundles.spring.data)
    implementation(libs.bundles.springdoc)

    constraints {
        implementation(libs.bundles.awssdk)
    }

    testImplementation("org.springframework.boot:spring-boot-starter-test")
}
