/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(project(":domain"))
    implementation("com.google.cloud:google-cloud-document-ai:2.67.0")
    testImplementation(libs.bundles.testgoodies)
}
